import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/illustration-aqsa 3.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { use, useState } from "react";
export default function Home() {
  const [darkMode, setDarkMode]= useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Aqsa Aqeel Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40">
        <section className="h-screen min-h-screen flex flex-col">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">Aqsa Aqeel</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={()=> setDarkMode(darkMode => !darkMode)} className="cursor-pointer text-xl" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 bg-cyan-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Aqsa Aqeel
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl">Frontend Developer</h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto">
              Frontend conneuseur with a love for design and building beautiful
              apps. Aqsa loves how code obeys everything she asks it for. When
              she is not coding, she is video editing or writing. Her self
              learning journey has also lead to cooking food.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillLinkedin />
            <AiFillTwitterCircle />
            <AiFillYoutube />
          </div>
          <div className="w-100 h-auto pb-10">
            <div className="relative mx-auto rounded-full h-60 w-60 py-10 mt-5 md:w-80 md:h-80">
              <Image
                className="rounded-full"
                fill
                style={{ objectFit: "cover" }}
                src={deved}
              />
            </div>
          </div>
          <section>
            <h3 className="text-3xl py-1">What do I do</h3>
            <p className="text-md py-2 leading-8 text-gray-80">
              Ever since a kid, I have been fascinated with websites design and
              engineering in general. And so growing up, I chose{" "}
              <span className="text-teal-500">frontend development</span>{" "}
              because it serves as a bridge of both these worlds.
            </p>
            <p className="text-md py-2 leading-8 text-gray-80">
              I have spent the last year learning React and JavaScript and
              gathered a lot of frontend experience. So much so, that now I can
              transition to any kind of framwork easily. I have also worked as a{" "}
              <span className="text-teal-500">frontend intern</span> at a remote
              startup. This internship made me dive into the professional world
              of frontend and I learnt about how things work in the industry.
            </p>
          </section>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={design} width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2">Beautiful Designs</h3>
              <p className="py-2">
                  Creating designs or whatever
              </p>
              <h4 className="py-4 text-teal-600">Design tools</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Photoshop</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={code} width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2">Beautiful Designs</h3>
              <p className="py-2">
                  Creating designs or whatever
              </p>
              <h4 className="py-4 text-teal-600">Design tools</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Photoshop</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={consulting} width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2">Beautiful Designs</h3>
              <p className="py-2">
                  Creating designs or whatever
              </p>
              <h4 className="py-4 text-teal-600">Design tools</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Photoshop</p>
            </div>
          </div>
          <div>
          <h3 className="text-3xl py-1">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-80">
              Ever since a kid, I have been fascinated with websites design and
              engineering in general. And so growing up, I chose{" "}
              <span className="text-teal-500">frontend development</span>{" "}
              because it serves as a bridge of both these worlds.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image src = {web1} className="rounded-lg object-cover" width ={'100%'} height ={"100%"}/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src = {web2} className="rounded-lg object-cover" width ={'100%'} height ={"100%"}/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src = {web3} className="rounded-lg object-cover" width ={'100%'} height ={"100%"}/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src = {web4} className="rounded-lg object-cover" width ={'100%'} height ={"100%"}/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src = {web5} className="rounded-lg object-cover" width ={'100%'} height ={"100%"}/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src = {web6} className="rounded-lg object-cover" width ={'100%'} height ={"100%"}/>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
